export const alumnoModel = {
    nombre: '',
    apellido: '',
    tipoDocumento: 'DNI',
    documento: '',
    fechaNacimiento: '',
    sexo: 'Masculino',
    lugarNacimiento: '',
    telefonoFijo: '',
    telefonoMovil: '',
    domicilio: '',
    numero: '',
    departamento: '',
    piso: '',
    partidaNacimiento: false,
    fotocopiaDNI: false,
    fotocopiaCUIL: false,
    foto4x4: false,
    contrato: false,
    observaciones: '',
    cursoId: '',
    materias: [],
    tutores: []
}
