export const customStyles = {
        top: '50%',
        left: '50%',
        right: 'auto',
        bottom: 'auto',
        transform: 'translate(-50%, -50%)',
        maxWidth: '360px',
        maxHeight: '740px',
        bgcolor: 'white',
        position: 'absolute',
        borderRadius: '5px',
        width: 400,
        boxShadow: 24,
        p: 4,
};